pipeline {
  agent any
  stages {  
    
   
     stage('Jacoco Coverage Report') {
            steps{
                    jacoco()
        }
    }
      
    stage('SonarQube'){
        steps{
                bat label: '', script: '''mvn sonar:sonar \
                -Dsonar.host.url=http://localhost:9000 \
                -Dsonar.login=75c1736028ebf73ae7352267f305ec535ac3e4e8'''
            }
           }     
  
   }
}